#!/usr/bin/env python3
"""Fetch the ward's four typefaces once, so no visitor's browser ever asks Google for them.

Archivo, IBM Plex Mono, IBM Plex Sans and IBM Plex Sans Thai are all under the SIL Open Font
License 1.1, which allows redistribution. Run from this directory; it rewrites fonts.css and the
.woff2 files beside it. The server compiles them in (see FONTS in src/main.rs).
"""
import hashlib, re, urllib.request

CSS = ("https://fonts.googleapis.com/css2?family=Archivo:wght@600;700;800"
       "&family=IBM+Plex+Mono:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600"
       "&family=IBM+Plex+Sans+Thai:wght@400;500;600;700&display=swap")
# A current browser's User-Agent, so Google answers with woff2 and unicode-range subsets.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")

def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()

css = get(CSS).decode()
def local(m):
    body = get(m.group(1))
    name = hashlib.sha256(body).hexdigest()[:16] + ".woff2"
    open(name, "wb").write(body)
    return f"url(/fonts/{name})"
css = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", local, css)
open("fonts.css", "w").write("/* Served by the ward itself. SIL Open Font License 1.1. See fetch-fonts.py. */\n" + css)
print(len(re.findall(r"url\(/fonts/", css)), "faces")

# The table the server compiles in: every file fonts.css names, and nothing else.
names = sorted(set(re.findall(r"url\(/fonts/([0-9a-f]{16}\.woff2)\)", css)))
rows = "\n".join(f'    ("{n}", include_bytes!("../static/fonts/{n}")),' for n in names)
open("../../src/fonts.rs", "w").write(
    "//! The ward's typefaces, served by the ward — generated by static/fonts/fetch-fonts.py.\n"
    "//! SIL Open Font License 1.1. Do not edit by hand; re-run the script.\n\n"
    'pub const CSS: &str = include_str!("../static/fonts/fonts.css");\n\n'
    "pub const FILES: &[(&str, &[u8])] = &[\n" + rows + "\n];\n")
