//! vitals.academy/blog — generated by `crates/vitals-web/blog/build.py` from `posts.json`.
//! Edit the posts there and rebuild; this file is overwritten.

pub const PAGES: &[(&str, &str)] = &[
    ("/blog", include_str!("../static/blog/index.html")),
    ("/blog/day-2-vitals-world-is-open", include_str!("../static/blog/day-2-vitals-world-is-open.html")),
    ("/blog/day-3-the-globe-is-live", include_str!("../static/blog/day-3-the-globe-is-live.html")),
    ("/blog/day-4-the-case-factory", include_str!("../static/blog/day-4-the-case-factory.html")),
    ("/blog/day-5-the-patient-factory", include_str!("../static/blog/day-5-the-patient-factory.html")),
    ("/blog/day-6-what-the-chain-does", include_str!("../static/blog/day-6-what-the-chain-does.html")),
    ("/blog/vitals-colosseum-eternal-entry", include_str!("../static/blog/vitals-colosseum-eternal-entry.html")),
    ("/blog/a-model-that-cannot-hallucinate", include_str!("../static/blog/a-model-that-cannot-hallucinate.html")),
    ("/blog/the-ward-opened", include_str!("../static/blog/the-ward-opened.html")),
    ("/blog/nobody-came", include_str!("../static/blog/nobody-came.html")),
    ("/blog/eleven-shifts", include_str!("../static/blog/eleven-shifts.html")),
    ("/blog/fifty-seven-had-nobody", include_str!("../static/blog/fifty-seven-had-nobody.html")),
    ("/blog/week-2-a-receipt-that-refuses-to-guess", include_str!("../static/blog/week-2-a-receipt-that-refuses-to-guess.html")),
    ("/blog/week-3-the-plan", include_str!("../static/blog/week-3-the-plan.html")),
];

pub const IMAGES: &[(&str, &[u8], &str)] = &[
    ("/blog/img/63-1.jpg", include_bytes!("../blog/img/63-1.jpg"), "image/jpeg"),
    ("/blog/img/112-1.gif", include_bytes!("../blog/img/112-1.gif"), "image/gif"),
    ("/blog/img/158-1.gif", include_bytes!("../blog/img/158-1.gif"), "image/gif"),
    ("/blog/img/209-1.jpg", include_bytes!("../blog/img/209-1.jpg"), "image/jpeg"),
    ("/blog/img/209-2.jpg", include_bytes!("../blog/img/209-2.jpg"), "image/jpeg"),
    ("/blog/img/209-3.jpg", include_bytes!("../blog/img/209-3.jpg"), "image/jpeg"),
    ("/blog/img/209-4.jpg", include_bytes!("../blog/img/209-4.jpg"), "image/jpeg"),
    ("/blog/img/256-1.jpg", include_bytes!("../blog/img/256-1.jpg"), "image/jpeg"),
    ("/blog/img/256-2.jpg", include_bytes!("../blog/img/256-2.jpg"), "image/jpeg"),
    ("/blog/img/256-3.jpg", include_bytes!("../blog/img/256-3.jpg"), "image/jpeg"),
    ("/blog/img/256-4.jpg", include_bytes!("../blog/img/256-4.jpg"), "image/jpeg"),
    ("/blog/img/354-1.jpg", include_bytes!("../blog/img/354-1.jpg"), "image/jpeg"),
    ("/blog/img/413-1.jpg", include_bytes!("../blog/img/413-1.jpg"), "image/jpeg"),
    ("/blog/img/413-2.jpg", include_bytes!("../blog/img/413-2.jpg"), "image/jpeg"),
    ("/blog/img/467-1.jpg", include_bytes!("../blog/img/467-1.jpg"), "image/jpeg"),
    ("/blog/img/525-1.jpg", include_bytes!("../blog/img/525-1.jpg"), "image/jpeg"),
    ("/blog/img/602-1.jpg", include_bytes!("../blog/img/602-1.jpg"), "image/jpeg"),
    ("/blog/img/602-2.jpg", include_bytes!("../blog/img/602-2.jpg"), "image/jpeg"),
    ("/blog/img/662-1.jpg", include_bytes!("../blog/img/662-1.jpg"), "image/jpeg"),
];

pub const NOT_FOUND: &str = include_str!("../static/blog/not-found.html");

pub enum Page {
    Html(&'static str),
    Image(&'static [u8], &'static str),
}

/// Whether a path belongs to the blog: `/blog` and everything under `/blog/`, nothing else.
pub fn is_blog(path: &str) -> bool {
    path == "/blog" || path.starts_with("/blog/")
}

/// The page or image at a blog path, with or without a trailing slash; `None` is a 404.
pub fn serve(path: &str) -> Option<Page> {
    let path = match path.strip_suffix('/') {
        Some(p) if !p.is_empty() => p,
        _ => path,
    };
    PAGES.iter().find(|(p, _)| *p == path).map(|(_, h)| Page::Html(h)).or_else(|| {
        IMAGES.iter().find(|(p, ..)| *p == path).map(|(_, b, t)| Page::Image(b, t))
    })
}
