//! Play EP1 in a browser.
//!
//! One process: the same `vitals-sce` automaton the verifier runs, a session per player, and a
//! tape that is recorded as you play. Reach a terminal state and the tape reduces to a leaf —
//! the same bytes `vitals-replay` would produce from the same tape, because it is the same code.
//!
//! Deliberately small. No framework, no database, no build step: tiny_http, a single HTML page,
//! and sessions in a map. The point is to make the automaton playable, not to ship a platform.

mod chain;
use vitals_web::{meter, news2, patient, store};

use serde::Serialize;
use std::collections::HashMap;
use std::time::{Duration, Instant};
use std::sync::{Arc, Mutex};
use tiny_http::{Header, Method, Response, Server};
use vitals_progress::record::AttemptRecord;
use vitals_progress::Difficulty;
use vitals_replay::{hex, leaf, record_for, replay, resume, sce_hash, Step};
use vitals_sce::{render_beat, Sce, SceState};

const PAGE: &str = include_str!("../static/index.html");
/// The front door. The product page lives at `/` and the game one click behind it at `/play`,
/// because the first visitor a public URL meets is as likely to be a reviewer deciding what this
/// company is as a learner deciding whether to press play — and the bay answers only the second.
const LANDING: &str = include_str!("../static/landing.html");
/// The pitch, served by the same process that serves the bay.
///
/// Baked in rather than read from disk. Twice in one day a path that existed on the build machine
/// did not exist in the container — the patient could not speak, and the film would not play — and
/// both failures looked like something else entirely. A deck cannot go missing halfway through a
/// pitch if there is no file for it to go missing from.
const DECK: &str = include_str!("../../../pitch/deck.html");
const SCRIPT: &str = include_str!("../../../pitch/script.html");
/// Arrow keys, a counter and a progress rule, appended to the deck when it is served.
///
/// Kept out of `pitch/deck.html` deliberately: that file is regenerated by scripts, so anything
/// written into it is one regeneration away from being lost — and `build-pdf.sh` renders it
/// straight off disk through a `file://` URL, where a printed deck has no use for arrow keys.
const PRESENT: &str = include_str!("../static/present.html");
/// The real bedside monitor, vendored from Embla's device page.
///
/// Not reimplemented: it already draws ECG morphology in milliseconds (P 80ms, PR 160ms, a QRS
/// that stays 90ms at any rate), sweeps a cursor the way a monitor does instead of scrolling, and
/// knows VF from asystole from PEA. A hand-rolled trace reads as fake to a clinician instantly —
/// which is exactly what the first version of this app did.
const MONITOR: &str = include_str!("../static/device/monitor.html");
const VENT: &str = include_str!("../static/device/vent.html");
const PUMP: &str = include_str!("../static/device/pump.html");

/// Where the rendered EP1 clips live.
///
/// Served from disk rather than baked into the binary: 20 clips is 43MB, and the point of
/// reusing already-rendered film is that it does not need to be moved around again.
fn clips_dir() -> std::path::PathBuf {
    std::env::var("VITALS_CLIPS")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| {
            std::path::PathBuf::from("/Users/mimir/Developer/Embla/app-swift/Resources/cutscenes/ep1")
        })
}

/// The patient, keyed by the clinical status the automaton is reporting.
///
/// This is the Director's job in the real Story Mode, reduced to its smallest useful form: the
/// engine says how she is, and the screen shows it. The stills are EP1's, already rendered.
const STILLS: &[(&str, &[u8])] = &[
    ("stable", include_bytes!("../static/img/stable.jpg")),
    ("deteriorating", include_bytes!("../static/img/deteriorating.jpg")),
    ("critical", include_bytes!("../static/img/critical.jpg")),
    ("arrest", include_bytes!("../static/img/arrest.jpg")),
    ("improving", include_bytes!("../static/img/improving.jpg")),
    ("recovered", include_bytes!("../static/img/recovered.jpg")),
    ("dead", include_bytes!("../static/img/dead.jpg")),
];

struct Session {
    /// Which scenario, so a resumed run reloads the same automaton it was played against.
    ep: String,
    /// Whose case this is. `None` for a kiosk or a browser that cannot make a key — then the
    /// session id is the only secret, which is why it is not a counter any more.
    owner: Option<String>,
    state: SceState,
    tape: Vec<Step>,
    beats: Vec<String>,
    sce_json: String,
    scenario: String,
    difficulty: Difficulty,
    anchored: bool,
    /// The declaration this run answers: (commitment hash, the slot it landed at, the nonce).
    ///
    /// Written when the player's commit transaction confirms, read when the record is built —
    /// the leaf must carry the same (hash, slot) the program stamped, or the server's local
    /// leaf list forks from the tree on chain and every later proof fails. The nonce stays
    /// here so the run can be revealed later; it never reaches the chain.
    commit: Option<([u8; 32], u64, [u8; 32])>,
    /// The conversation, kept only so she remembers what she already told you. It is never
    /// hashed, never anchored, and never leaves this process.
    said: Vec<(String, String)>,
    /// Last time this run was written to disk. Ticks arrive about once a second and are cheap to
    /// lose — the tape is the truth and a few seconds of it is a few seconds of sim — so they are
    /// throttled. Anything the player actually *did* is written immediately.
    saved_at: Option<std::time::Instant>,
}

/// A run as it sits on disk.
///
/// The state is not here, because the state is not a fact — it is what the tape computes. Storing
/// it would create a second copy that can disagree with the tape, which is the failure this repo
/// has already had once. On load the tape is replayed and the machine is rebuilt from it.
#[derive(serde::Serialize, serde::Deserialize)]
struct Saved {
    ep: String,
    #[serde(default)]
    owner: Option<String>,
    /// The scenario this run was played against. A rewritten scenario must not silently resume a
    /// run into a different automaton — the outcome would be re-derived under rules the player
    /// never played.
    sce_hash: String,
    tape: Vec<Step>,
    said: Vec<(String, String)>,
    anchored: bool,
    #[serde(default)]
    commit: Option<([u8; 32], u64, [u8; 32])>,
}

const SESSIONS: &str = "sessions";

impl Session {
    /// May this caller touch this case?
    ///
    /// An owned case answers only to its owner. An anonymous one answers to whoever holds the id,
    /// which is safe only because the id is now 128 bits of randomness rather than `s7`.
    fn answers_to(&self, who: Option<&str>) -> bool {
        match (&self.owner, who) {
            (None, _) => true,
            (Some(mine), Some(you)) => mine == you,
            (Some(_), None) => false,
        }
    }
}

/// A session id nobody can walk to from the one before it.
///
/// It used to be `s1`, `s2`, `s3`. On a server two people can reach, a counter is an index of
/// everybody else's cases — and every route looked a session up by id and did as it was told.
fn fresh_id() -> String {
    use solana_sdk::signature::{Keypair, Signer};
    hex_bytes(&Keypair::new().pubkey().to_bytes()[..16])
}

/// The same answer for "there is no such case" and "that case is not yours".
///
/// Two different answers would let a guesser tell live ids from dead ones, which is most of the
/// work of finding somebody to interfere with.
fn no_such_session() -> Response<std::io::Cursor<Vec<u8>>> {
    json(serde_json::json!({ "error": "no such session" }))
}

impl Session {
    fn saved(&self) -> Saved {
        Saved {
            ep: self.ep.clone(),
            owner: self.owner.clone(),
            sce_hash: hex(&sce_hash(&self.sce_json)),
            tape: self.tape.clone(),
            said: self.said.clone(),
            anchored: self.anchored,
            commit: self.commit,
        }
    }

    /// Rebuild a run from disk by replaying its tape.
    fn restore(saved: Saved) -> Result<Session, String> {
        let sce_json = std::fs::read_to_string(scenario_path(&saved.ep)).map_err(|e| e.to_string())?;
        let want = hex(&sce_hash(&sce_json));
        if want != saved.sce_hash {
            return Err(format!("scenario {} changed under this run", saved.ep));
        }
        let (state, r) = resume(&sce_json, &saved.tape)?;
        Ok(Session {
            ep: saved.ep.clone(),
            owner: saved.owner.clone(),
            state,
            beats: r.beats,
            tape: saved.tape,
            sce_json,
            scenario: title(&saved.ep).to_string(),
            difficulty: difficulty(&saved.ep),
            anchored: saved.anchored,
            commit: saved.commit,
            said: saved.said,
            saved_at: Some(std::time::Instant::now()),
        })
    }
}

/// Write a run to disk. `urgent` is false only for a bare tick.
fn persist(store: &store::Store, id: &str, s: &mut Session, urgent: bool) {
    const THROTTLE: std::time::Duration = std::time::Duration::from_secs(3);
    if !urgent {
        if let Some(t) = s.saved_at {
            if t.elapsed() < THROTTLE {
                return;
            }
        }
    }
    if let Err(e) = store.put(SESSIONS, id, &s.saved()) {
        eprintln!("could not save session {id}: {e}");
    }
    s.saved_at = Some(std::time::Instant::now());
}

/// The anchoring tree this server is filling.
///
/// Shared by every player on the box, which is what the on-chain seeds say: the tree is keyed by
/// its id alone, and a Merkle proof needs every leaf in it. What is *not* shared is who a run
/// belongs to — the claim and progress accounts are seeded on the player, so two people on one
/// server have two separate records.
///
/// It has to outlive the process. The leaves are on chain either way, but the proof is built from
/// this list, so a server that forgets them can no longer prove anything it anchored.
#[derive(Default, serde::Serialize, serde::Deserialize)]
struct Tree {
    tree_id: u64,
    leaves: Vec<[u8; 32]>,
}

const TREE: &str = "tree";

#[derive(Serialize)]
struct View {
    scenario: String,
    hr: f64,
    sbp: f64,
    dbp: f64,
    spo2: f64,
    rr: f64,
    temp: f64,
    gcs: u8,
    status: String,
    beats: Vec<String>,
    harm: Vec<String>,
    outcome: Option<String>,
    elapsed: f64,
    /// Only once the run is over — a run in progress has nothing to anchor yet.
    leaf: Option<String>,
    sce_hash: String,
    /// What is on the patient right now, in the order it went on.
    equipment: Vec<Kit>,
    /// Everything that happened, stamped with the scenario clock — the chart.
    chart: Vec<Note>,
    /// NEWS2 — what a ward actually escalates on, computed from the observations above.
    ///
    /// This used to be a "stability" percentage invented here, and it averaged: a patient with
    /// one catastrophic derangement and six normal readings came out looking well. That is the
    /// mistake the real score exists to prevent.
    ///
    /// `None` once she has died. It is an *early warning* score — it exists to decide whether
    /// somebody needs to come and how fast, and there is nothing left to warn about.
    news: Option<News>,
}

#[derive(Serialize)]
struct News {
    total: u32,
    worst: u32,
    band: &'static str,
    response: &'static str,
}

#[derive(Serialize, Clone)]
struct Kit {
    id: String,
    setting: Option<f64>,
    since: f64,
}

#[derive(Serialize, Clone)]
struct Note {
    t: f64,
    kind: String,
    text: String,
}


impl Session {
    fn view(&self) -> View {
        let v = self.state.vitals;
        let elapsed: f64 = self
            .tape
            .iter()
            .map(|s| match s {
                Step::Tick(dt) => *dt,
                Step::Do(_) | Step::Act { .. } | Step::Ask(_) | Step::Set(..) | Step::Off(_) => 0.0,
            })
            .sum();
        let outcome = self.state.outcome().map(|o| format!("{o:?}"));
        // Derived by replaying the tape, not by reading the live state. Assembling a Replay by
        // hand here would show the player a leaf computed one way while the verifier computes it
        // another, and a leaf that depends on which side of the wire you stand on proves nothing.
        let leaf_hex = outcome.as_ref().and_then(|_| {
            let r = replay(&self.sce_json, &self.tape).ok()?;
            Some(hex(&leaf(&sce_hash(&self.sce_json), &self.tape, &r)))
        });
        // Supplemental oxygen is worth points of its own: holding 96% on a mask is not the same
        // patient as holding 96% on air, and the score is built to say so.
        let on_oxygen = self.state.has_equipment("o2") || self.state.has_equipment("ett");
        let obs = news2::Obs {
            rr: v.rr, spo2: v.spo2, on_oxygen, sbp: v.sbp, hr: v.hr, temp: v.temp, gcs: v.gcs,
        };
        let n = news2::score(&obs);

        View {
            scenario: self.scenario.clone(),
            hr: v.hr.round(),
            sbp: v.sbp.round(),
            dbp: v.dbp.round(),
            spo2: v.spo2.round(),
            rr: v.rr.round(),
            temp: (v.temp * 10.0).round() / 10.0,
            gcs: v.gcs,
            status: format!("{:?}", self.state.status),
            beats: self.beats.clone(),
            harm: self.state.harm_events.clone(),
            outcome,
            elapsed,
            leaf: leaf_hex,
            sce_hash: hex(&sce_hash(&self.sce_json)),
            equipment: self
                .state
                .equipment()
                .iter()
                .map(|e| Kit { id: e.id.clone(), setting: e.setting, since: e.since_sec })
                .collect(),
            chart: self
                .state
                .events()
                .iter()
                .map(|e| Note { t: e.t_sec, kind: e.kind.clone(), text: e.text.clone() })
                .collect(),
            news: (self.state.status != vitals_sce::PatientStatus::Dead).then(|| News {
                total: n.total,
                worst: n.worst,
                band: n.band.as_str(),
                response: n.band.response(),
            }),
        }
    }
}

/// Where the scenarios and the story files live.
///
/// CARGO_MANIFEST_DIR is baked in at build time and names the machine that compiled this. In a
/// container that path does not exist, so everything read at runtime goes through here.
fn scenario_root() -> std::path::PathBuf {
    match std::env::var("VITALS_SCENARIOS") {
        Ok(d) => std::path::PathBuf::from(d),
        Err(_) => std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../.."),
    }
}

fn scenario_path(id: &str) -> std::path::PathBuf {
    let root = scenario_root();
    match id {
        "ep2" => root.join("demo/scenarios/ep2-stemi.json"),
        "ep3" => root.join("demo/scenarios/ep3-epiglottitis.json"),
        "ep4" => root.join("demo/scenarios/ep4-pulmonary-embolism.json"),
        "ep5" => root.join("demo/scenarios/ep5-the-night-the-stars-fell.json"),
        _ => root.join("conformance/sce-anaphylaxis-ep1.json"),
    }
}

fn title(id: &str) -> &'static str {
    match id {
        "ep2" => "EP2 · Time Is Muscle",
        "ep3" => "EP3 · Don't Make Him Cry",
        "ep4" => "EP4 · The Masquerader",
        "ep5" => "EP5 · The Night the Stars Fell",
        _ => "EP1 · The Last Bite",
    }
}

fn difficulty(ep: &str) -> Difficulty {
    match ep {
        "ep2" => Difficulty::Intern,
        "ep3" | "ep4" | "ep5" => Difficulty::Resident,
        _ => Difficulty::Student,
    }
}

fn new_session(ep: &str) -> Result<Session, String> {
    let sce_json = std::fs::read_to_string(scenario_path(ep)).map_err(|e| e.to_string())?;
    let sce = Sce::from_json(&sce_json).map_err(|e| e.to_string())?;
    Ok(Session {
        ep: ep.to_string(),
        owner: None,
        state: SceState::new(sce),
        tape: Vec::new(),
        beats: Vec::new(),
        sce_json,
        scenario: title(ep).to_string(),
        difficulty: difficulty(ep),
        anchored: false,
        said: Vec::new(),
        saved_at: None,
        commit: None,
        })
}

fn html(body: &str) -> Response<std::io::Cursor<Vec<u8>>> {
    Response::from_string(body).with_header(
        Header::from_bytes(&b"Content-Type"[..], &b"text/html; charset=utf-8"[..]).unwrap(),
    )
}

fn json(v: impl Serialize) -> Response<std::io::Cursor<Vec<u8>>> {
    let body = serde_json::to_string(&v).unwrap_or_else(|_| "{}".into());
    Response::from_string(body)
        .with_header(Header::from_bytes(&b"Content-Type"[..], &b"application/json"[..]).unwrap())
}

/// A JSON reply that is not a 200. The body still carries the whole story — a metering refusal
/// is a page the front end renders, not a status code it apologises for.
fn json_code(v: impl Serialize, code: u16) -> Response<std::io::Cursor<Vec<u8>>> {
    json(v).with_status_code(code)
}

/// Who is calling, as far as rate limiting is concerned.
///
/// Behind Cloud Run the socket peer is the load balancer, and the visitor is the first entry of
/// `X-Forwarded-For` — later entries are whatever proxies appended, and the *last* one is the
/// only one Google vouches for, but for a politeness window the first is the honest choice: it
/// is the same for one browser and different for two households. Player keys and session ids are
/// deliberately not used here; a browser mints those for free.
fn client_addr(req: &tiny_http::Request) -> String {
    req.headers()
        .iter()
        .find(|h| h.field.equiv("x-forwarded-for"))
        .and_then(|h| h.value.as_str().split(',').next().map(|s| s.trim().to_string()))
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| {
            req.remote_addr().map(|a| a.ip().to_string()).unwrap_or_else(|| "unknown".into())
        })
}

fn param(url: &str, key: &str) -> Option<String> {
    url.split_once('?')?.1.split('&').find_map(|kv| {
        let (k, v) = kv.split_once('=')?;
        (k == key).then(|| percent_decode(v))
    })
}

/// Enough percent-decoding for a typed clinical order. No dependency for this.
fn percent_decode(s: &str) -> String {
    let b = s.as_bytes();
    let mut out = String::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        match b[i] {
            b'+' => {
                out.push(' ');
                i += 1;
            }
            b'%' if i + 2 < b.len() => {
                match u8::from_str_radix(std::str::from_utf8(&b[i + 1..i + 3]).unwrap_or("zz"), 16) {
                    Ok(c) => {
                        out.push(c as char);
                        i += 3;
                    }
                    Err(_) => {
                        out.push('%');
                        i += 1;
                    }
                }
            }
            c => {
                out.push(c as char);
                i += 1;
            }
        }
    }
    out
}

/// Endpoints that spend something — the server's signature, or the GPU.
///
/// Playing is open because a kiosk should just work. Signing a transaction on request is not,
/// and "whoever can reach the port" is not an authorisation model.
fn guarded(path: &str) -> bool {
    matches!(path, "/api/anchor" | "/api/claim" | "/api/commit" | "/api/say")
}

fn bearer_ok(req: &tiny_http::Request, token: &Option<String>) -> bool {
    let Some(want) = token else { return true };
    req.headers()
        .iter()
        .find(|h| h.field.equiv("authorization"))
        .map(|h| h.value.as_str().trim())
        .map(|v| v.strip_prefix("Bearer ").unwrap_or(v) == want)
        .unwrap_or(false)
}

fn main() {
    // Not 8090. On the machine this is developed on that port is already three things — a
    // syn-sentry web app, an eir-fhir container publishing on the host, and the service port the
    // hermodr fleet uses inside the cluster. A default that collides with the neighbours is a
    // default that fails on the one day nobody is watching.
    let addr = bind_addr(
        std::env::var("PORT").ok().as_deref(),
        std::env::var("VITALS_WEB_BIND").ok().as_deref(),
    );
    let token = std::env::var("VITALS_TOKEN").ok().filter(|s| !s.is_empty());
    let loopback = addr.starts_with("127.") || addr.starts_with("localhost");
    if !loopback && token.is_none() {
        // Refusing to start is the only honest option. Bound to a public interface with no token,
        // anyone who finds the port can make this process sign transactions with its key.
        eprintln!("refusing to bind {addr} without VITALS_TOKEN — anyone reaching it could make \
                   this server sign with its key. Set VITALS_TOKEN, or bind to 127.0.0.1.");
        std::process::exit(2);
    }
    let server = match Server::http(&addr) {
        Ok(s) => s,
        // The raw panic said "Address already in use" and nothing about who has it.
        Err(e) => {
            eprintln!("cannot bind {addr}: {e}\n\
                       something else is on that port — try `lsof -nP -iTCP:{port} -sTCP:LISTEN`, \
                       or set VITALS_WEB_BIND to a free one.",
                      port = addr.rsplit(':').next().unwrap_or("?"));
            std::process::exit(2);
        }
    };

    let state_dir = std::env::var("VITALS_STATE_DIR").unwrap_or_else(|_| "state".into());
    let store = store::Store::open(std::path::PathBuf::from(&state_dir))
        .unwrap_or_else(|e| panic!("cannot open {state_dir}: {e}"));
    // A run nobody has touched in a day is a closed tab, not a patient.
    let swept = store.sweep(SESSIONS, std::time::Duration::from_secs(24 * 60 * 60));

    let mut restored = HashMap::new();
    let mut broken = 0usize;
    for (id, saved) in store.list::<Saved>(SESSIONS) {
        match Session::restore(saved) {
            Ok(s) => {
                restored.insert(id, s);
            }
            Err(e) => {
                // Loud, and dropped. A run that will not replay is exactly the thing this repo
                // must not paper over: it means the tape and the automaton disagree.
                eprintln!("dropping session {id}: {e}");
                store.del(SESSIONS, &id);
                broken += 1;
            }
        }
    }
    // No counter to carry across a restart any more: ids are random, so a restored run cannot
    // collide with a fresh one and there is nothing to resume from.
    println!(
        "state      {} · {} run(s) resumed{}{}",
        store.describe(),
        restored.len(),
        if swept > 0 { format!(" · {swept} expired") } else { String::new() },
        if broken > 0 { format!(" · {broken} unreplayable") } else { String::new() },
    );
    let sessions: Arc<Mutex<HashMap<String, Session>>> = Arc::new(Mutex::new(restored));

    // What this bay may spend, resumed from the store so a deploy does not reset the month.
    let mut meter = meter::Meter::open(&store);
    println!("meter      {}", meter.describe());

    // Through the same root as the scenarios. This was the other baked-in build path, and it is
    // why the container had a patient who could not speak even with a gateway to speak through.
    let story = scenario_root().join("demo/ep1-en.json");
    let patient = patient::Patient::connect(&story);
    match &patient {
        Some(p) => {
            let via = match p.backend() {
                patient::Backend::Local => "local model via Heimdall",
                patient::Backend::Cloud => "cloud model (local unreachable — fallback)",
            };
            println!("patient    {} — {via}", p.name());
        }
        None => println!("patient    no voice — set HEIMDALL_API_KEY (local) or VITALS_VERTEX_URL (cloud)"),
    }

    let chain = chain::Chain::connect();
    // Resume the tree this server was filling. Starting a new one every boot would strand every
    // leaf already anchored, because the proof is built from the leaf list and the old list is
    // what those leaves were anchored into.
    //
    // Keyed to this deployment rather than to a fixed name: two servers sharing a store used to
    // share the list and overwrite each other. Without a chain there is nothing to anchor into,
    // so the key is irrelevant and a fixed one keeps offline runs working.
    let tree_key = match &chain {
        Some(c) => {
            let (relay, program, rpc) = c.deployment();
            store::tree_key(&relay, &program, &rpc)
        }
        None => "offline".to_string(),
    };
    let tree = Arc::new(Mutex::new(store.get::<Tree>(TREE, &tree_key).unwrap_or_default()));
    match &chain {
        Some(c) => {
            let mut t = tree.lock().unwrap();
            if t.tree_id == 0 {
                t.tree_id = c.slot();
            }
            println!("chain      connected · slot {} · tree #{} · {} leaf/leaves",
                     c.slot(), t.tree_id, t.leaves.len());
            println!("relay      {} — pays fees, holds no player key", c.relay_pubkey());
        }
        None => println!("chain      not connected — set VITALS_PROGRAM_ID and start a validator to anchor"),
    }
    // Signed halves waiting on the browser, keyed by player. Never persisted: a blockhash goes
    // stale in about a minute, so a pending transaction that outlives the process is worthless.
    let pendings: Arc<Mutex<HashMap<String, PendingWork>>> = Arc::new(Mutex::new(HashMap::new()));

    match (&token, loopback) {
        (Some(_), _) => println!("auth       bearer token required on anchor · claim · say"),
        (None, true) => println!("auth       none — loopback only, so the blast radius is this machine"),
        (None, false) => unreachable!("refused to start above"),
    }
    // The address it actually got, not the one it asked for. Binding to :0 is how a test gets a
    // port nobody else has, and that is useless if the server then reports the zero back.
    let bound = server
        .server_addr()
        .to_ip()
        .map(|a| a.to_string())
        .unwrap_or_else(|| addr.clone());
    println!("Vitals — play at http://{bound}");

    // One slow local model, and /api/say holds a worker for as long as it takes. Without a
    // ceiling a single caller can occupy the GPU indefinitely.
    let mut said: Vec<Instant> = Vec::new();
    const SAY_PER_MIN: usize = 20;

    for req in server.incoming_requests() {
        let url = req.url().to_string();
        let path = url.split('?').next().unwrap_or("/").to_string();

        // The apex answers with the landing and nothing else; anything deeper moves permanently
        // to the game origin. 301 on purpose — the split is a recorded decision, not a phase —
        // and the landing carries its own short cache life so a proxy caching the apex never
        // holds anything of the game's.
        if host_of(&req) == APEX {
            let resp = match apex_target(&url) {
                None => html(LANDING).with_header(
                    Header::from_bytes(&b"Cache-Control"[..], &b"public, max-age=300"[..]).unwrap(),
                ),
                Some(to) => Response::from_string("")
                    .with_status_code(301)
                    .with_header(Header::from_bytes(&b"Location"[..], to.as_bytes()).unwrap()),
            };
            let _ = req.respond(resp);
            continue;
        }

        if guarded(&path) && !bearer_ok(&req, &token) {
            let _ = req.respond(
                Response::from_string(r#"{"error":"unauthorised"}"#)
                    .with_status_code(401)
                    .with_header(Header::from_bytes(&b"Content-Type"[..], &b"application/json"[..]).unwrap()),
            );
            continue;
        }
        if path == "/api/say" {
            said.retain(|t| t.elapsed() < Duration::from_secs(60));
            if said.len() >= SAY_PER_MIN {
                let _ = req.respond(json(serde_json::json!({ "error": "too many questions — give her a moment" })));
                continue;
            }
            said.push(Instant::now());
        }

        let resp = match (req.method(), path.as_str()) {
            (Method::Get, "/") => {
                let _ = req.respond(html(LANDING));
                continue;
            }
            (Method::Get, "/play") => {
                // The page is served by the same process that holds the token, so handing it over
                // does not widen anything: reaching the page and reaching the API are one boundary.
                let page = match &token {
                    Some(tk) => PAGE.replace("__VITALS_TOKEN__", tk),
                    None => PAGE.replace("__VITALS_TOKEN__", ""),
                };
                let _ = req.respond(
                    Response::from_string(page).with_header(
                        Header::from_bytes(&b"Content-Type"[..], &b"text/html; charset=utf-8"[..])
                            .unwrap(),
                    ),
                );
                continue;
            }
            // ── the pitch ───────────────────────────────────────────────────────
            // Unguarded, like the bay itself. Everything in the deck is already public in the
            // repository, so a token here would protect nothing and only stop it opening.
            (Method::Get, "/slides") | (Method::Get, "/slides/") => {
                let _ = req.respond(html(&format!("{DECK}{PRESENT}")));
                continue;
            }
            (Method::Get, "/slides/script") => {
                let _ = req.respond(html(SCRIPT));
                continue;
            }

            // ── film ────────────────────────────────────────────────────────────
            // Story Mode does not show a still and call it a patient: it loops a per-state clip
            // and cuts to a full-frame cutscene on a beat. Both are already rendered.
            (Method::Get, p) if p.starts_with("/clip/") => {
                let name = p.trim_start_matches("/clip/");
                // Nothing but a bare clip name — no traversal into the rest of the disk.
                let safe = name
                    .strip_suffix(".mp4")
                    .filter(|n| n.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'));
                match safe.and_then(|n| std::fs::read(clips_dir().join(format!("{n}.mp4"))).ok()) {
                    Some(bytes) => {
                        let _ = req.respond(
                            Response::from_data(bytes)
                                .with_header(Header::from_bytes(&b"Content-Type"[..], &b"video/mp4"[..]).unwrap())
                                .with_header(Header::from_bytes(&b"Cache-Control"[..], &b"public, max-age=86400"[..]).unwrap()),
                        );
                        continue;
                    }
                    None => Response::from_string("no such clip").with_status_code(404),
                }
            }
            (Method::Get, p) if p.starts_with("/img/") => {
                let key = p.trim_start_matches("/img/").trim_end_matches(".jpg");
                match STILLS.iter().find(|(k, _)| *k == key) {
                    Some((_, bytes)) => {
                        let _ = req.respond(
                            Response::from_data(*bytes)
                                .with_header(Header::from_bytes(&b"Content-Type"[..], &b"image/jpeg"[..]).unwrap())
                                .with_header(Header::from_bytes(&b"Cache-Control"[..], &b"public, max-age=86400"[..]).unwrap()),
                        );
                        continue;
                    }
                    None => Response::from_string("no such still").with_status_code(404),
                }
            }
            (Method::Get, p @ ("/device/monitor" | "/device/vent" | "/device/pump")) => {
                let page = match p {
                    "/device/vent" => VENT,
                    "/device/pump" => PUMP,
                    _ => MONITOR,
                };
                let _ = req.respond(Response::from_string(page).with_header(
                    Header::from_bytes(&b"Content-Type"[..], &b"text/html; charset=utf-8"[..]).unwrap(),
                ));
                continue;
            }
            (Method::Get, "/device/vitals") => {
                // The monitor identifies the bed by header, the way the device page already does.
                let sid = req
                    .headers()
                    .iter()
                    .find(|h| h.field.equiv("x-embla-session"))
                    .map(|h| h.value.as_str().to_string())
                    .unwrap_or_default();
                let map = sessions.lock().unwrap();
                match map.get(&sid) {
                    None => json(serde_json::json!({})),
                    Some(s) => {
                        let v = s.state.vitals;
                        let r = v.rhythm;
                        json(serde_json::json!({
                            "hr": v.hr, "spo2": v.spo2, "sbp": v.sbp, "dbp": v.dbp,
                            "rr": v.rr, "temp": v.temp, "gcs": v.gcs,
                            "status": format!("{:?}", s.state.status),
                            "rhythm": r.as_str(),
                            // A monitor that invents a pulse is worse than one that misses an
                            // arrest, so this comes from the rhythm rather than from the numbers.
                            "pulse": r.perfusing(),
                            "shockable": r.shockable(),
                            "paused": false,
                        }))
                    }
                }
            }
            (Method::Get, "/api/new") => {
                // A run is a stored document, and a loop hammering "new" is a bill with no
                // learner attached. The window only, never the ceiling: opening a run must
                // survive the month's voice budget running out.
                if let meter::Verdict::SlowDown { retry_secs } =
                    meter.allow_free(&format!("new:{}", client_addr(&req)), &store)
                {
                    let _ = req.respond(json_code(serde_json::json!({
                        "error": "too many new runs from this address — give it a minute",
                        "retry_in": retry_secs,
                    }), 429));
                    continue;
                }
                let ep = param(&url, "ep").unwrap_or_else(|| "ep1".into());
                match new_session(&ep) {
                    Ok(mut s) => {
                        s.owner = param(&url, "player").and_then(|p| pubkey(&p)).map(|k| k.to_string());
                        let id = fresh_id();
                        let view = s.view();
                        let mut map = sessions.lock().unwrap();
                        map.insert(id.clone(), s);
                        persist(&store, &id, map.get_mut(&id).expect("just inserted"), true);
                        drop(map);
                        json(serde_json::json!({ "id": id, "view": view }))
                    }
                    Err(e) => json(serde_json::json!({ "error": e })),
                }
            }
            (Method::Get, "/api/step") => {
                let id = param(&url, "id").unwrap_or_default();
                let caller = param(&url, "player");
                let mut map = sessions.lock().unwrap();
                match map.get_mut(&id).filter(|s| s.answers_to(caller.as_deref())) {
                    None => no_such_session(),
                    Some(s) => {
                        let acted = param(&url, "do").is_some();
                        if let Some(act) = param(&url, "do") {
                            let emitted = s.state.apply(&act);
                            s.beats.extend(emitted.iter().map(render_beat));
                            // Recognition happens here, once, and its answer goes on the tape beside the
                            // words. An order nobody understood is recorded as exactly that — an
                            // empty resolution — so replay stays faithful to a run in which nothing
                            // happened, even after the matcher learns the phrase.
                            let id = s.state.resolve(&act).unwrap_or_default();
                            s.tape.push(Step::acted(&act, &id));
                        }
                        if let Some(dt) = param(&url, "tick").and_then(|v| v.parse::<f64>().ok()) {
                            let emitted = s.state.tick(dt);
                            s.beats.extend(emitted.iter().map(render_beat));
                            s.tape.push(Step::Tick(dt));
                        }
                        let v = s.view();
                        persist(&store, &id, s, acted);
                        json(v)
                    }
                }
            }
            // ── the kit ─────────────────────────────────────────────────────────
            // Attaching a device is not a free-text order. It is a pick from a catalogue with a
            // setting, and the flowmeter has to read what the learner actually chose — the same
            // shape Embla's device tray uses, so the chart and a debrief can quote the number.
            (Method::Get, "/api/kit") => {
                let id = param(&url, "id").unwrap_or_default();
                let caller = param(&url, "player");
                let dev = param(&url, "dev").unwrap_or_default();
                let set = param(&url, "set").and_then(|v| v.parse::<f64>().ok());
                let off = param(&url, "off").is_some();
                let mut map = sessions.lock().unwrap();
                match map.get_mut(&id).filter(|s| s.answers_to(caller.as_deref())) {
                    None => no_such_session(),
                    Some(s) => {
                        if off {
                            s.state.detach(&dev);
                            s.tape.push(Step::Off(dev.clone()));
                        } else if s.state.has_equipment(&dev)
                            && (set.is_none() || s.state.equipment_setting(&dev) == set)
                        {
                            // Already on, at that number. Re-picking it is not a second dose —
                            // and re-running the intervention would re-attach at the scenario's
                            // canonical setting, so the chart would log a change that never
                            // happened, then log changing it back.
                        } else if s.state.has_equipment(&dev) {
                            // On already, different number: turn the dial, do not re-dose.
                            if let Some(v) = set {
                                s.state.attach(&dev, Some(v));
                                s.tape.push(Step::Set(dev.clone(), v));
                            }
                        } else if let Some(phrase) = kit_phrase(&dev, set) {
                            // Go through the matcher, so the physiology moves exactly as it would
                            // for someone who typed it. The picker is a convenience, not a bypass.
                            let emitted = s.state.apply(&phrase);
                            s.beats.extend(emitted.iter().map(render_beat));
                            s.tape.push(Step::did(&phrase));
                            // Then correct the reading to what was actually dialled in. attach()
                            // records it too, so the chart quotes the learner's number rather
                            // than the scenario's canonical dose.
                            if let Some(v) = set {
                                if s.state.has_equipment(&dev) && s.state.equipment_setting(&dev) != Some(v) {
                                    s.state.attach(&dev, Some(v));
                                    // On the tape too. Without this the correction lived only in
                                    // this process: the player saw 6 L/min, the tape replayed to
                                    // the scenario's 10, and the leaf certified the wrong run.
                                    s.tape.push(Step::Set(dev.clone(), v));
                                }
                            }
                        }
                        let v = s.view();
                        persist(&store, &id, s, true);
                        json(v)
                    }
                }
            }
            // What the run is told back. Derived from the tape, so anyone holding the tape and the
            // scenario re-derives the same debrief — it is evidence, not commentary.
            (Method::Get, "/api/debrief") => {
                let id = param(&url, "id").unwrap_or_default();
                let caller = param(&url, "player");
                let mut map = sessions.lock().unwrap();
                match map.get_mut(&id).filter(|s| s.answers_to(caller.as_deref())) {
                    None => no_such_session(),
                    Some(s) => match vitals_replay::debrief(&s.sce_json, &s.tape) {
                        Err(e) => json(serde_json::json!({ "error": e })),
                        Ok(d) => json(serde_json::json!({
                            "outcome": d.outcome,
                            "seconds": d.sim_seconds,
                            "expected": d.expected.iter().map(|e| serde_json::json!({
                                "id": e.id, "label": e.label, "why": e.why,
                                "within": e.within, "done_at": e.done_at,
                                "late": e.late, "late_by": e.late_by,
                            })).collect::<Vec<_>>(),
                            "avoided": d.avoided.iter().filter(|a| a.done_at.is_some())
                                .map(|a| serde_json::json!({
                                    "id": a.id, "label": a.label, "why": a.why, "done_at": a.done_at,
                                })).collect::<Vec<_>>(),
                            "harms": d.harms.iter().map(|h| serde_json::json!({
                                "text": h.text, "at": h.at, "caused_by": h.caused_by,
                            })).collect::<Vec<_>>(),
                            "statuses": d.statuses.iter().map(|sp| serde_json::json!({
                                "status": sp.status, "from": sp.from, "seconds": sp.seconds,
                            })).collect::<Vec<_>>(),
                        })),
                    },
                }
            }
            (Method::Get, "/api/tape") => {
                let id = param(&url, "id").unwrap_or_default();
                let caller = param(&url, "player");
                let map = sessions.lock().unwrap();
                match map.get(&id).filter(|s| s.answers_to(caller.as_deref())) {
                    None => no_such_session(),
                    // The tape in the same shape vitals-replay takes, so a player can hand it to
                    // someone else and have the leaf re-derived off this machine entirely.
                    Some(s) => json(serde_json::json!({
                        "scenario": s.scenario,
                        "sce_hash": hex(&sce_hash(&s.sce_json)),
                        "tape": s.tape.iter().map(|st| match st {
                            Step::Tick(dt) => serde_json::json!({"tick": dt}),
                            Step::Do(t) => serde_json::json!({"do": t}),
                            Step::Act { text, id } => serde_json::json!({"do": text, "act": id}),
                            Step::Ask(t) => serde_json::json!({"ask": t}),
                            Step::Set(id, v) => serde_json::json!({"set": id, "to": v}),
                            Step::Off(id) => serde_json::json!({"off": id}),
                        }).collect::<Vec<_>>()
                    })),
                }
            }
            (Method::Get, "/api/say") => {
                let id = param(&url, "id").unwrap_or_default();
                let caller = param(&url, "player");
                let q = param(&url, "q").unwrap_or_default();
                let Some(pt) = patient.as_ref() else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no gateway — she has no voice here" })));
                    continue;
                };
                // The bay is free and the inference is paid for by donations, so the spend is
                // metered per address and capped per month. The ceiling reply carries the whole
                // meter: the page turns it into "what this month funded", not a bare 429.
                match meter.allow(&client_addr(&req), &store) {
                    meter::Verdict::Ok => {}
                    meter::Verdict::SlowDown { retry_secs } => {
                        let _ = req.respond(json_code(serde_json::json!({
                            "error": "she needs a moment — you are asking faster than the bay allows",
                            "retry_in": retry_secs,
                        }), 429));
                        continue;
                    }
                    meter::Verdict::Ceiling => {
                        let _ = req.respond(json_code(serde_json::json!({
                            "error": "this month's compute is spent",
                            "ceiling": meter.view(),
                        }), 429));
                        continue;
                    }
                }
                // Snapshot what the model needs, then release the lock: a local 26B reply takes
                // seconds and the tick loop must not block behind it.
                let (hist, status, spo2) = {
                    let mut map = sessions.lock().unwrap();
                    let Some(s) = map.get_mut(&id).filter(|s| s.answers_to(caller.as_deref())) else {
                        let _ = req.respond(no_such_session());
                        continue;
                    };
                    // The question goes on the tape. The answer never will.
                    s.tape.push(Step::asked(&q));
                    (s.said.clone(), format!("{:?}", s.state.status), s.state.vitals.spo2)
                };
                // No hint on this path yet — the reveal-gate wiring passes one when it lands.
                match pt.say(&q, &hist, &status, spo2, None) {
                    Ok(reply) => {
                        // Counted only when she actually answered — a failed call is not billed
                        // to the month or to the visitor.
                        meter.spend(&store);
                        let mut map = sessions.lock().unwrap();
                        if let Some(s) = map.get_mut(&id) {
                            s.said.push(("user".into(), q));
                            s.said.push(("assistant".into(), reply.clone()));
                            persist(&store, &id, s, true);
                        }
                        json(serde_json::json!({ "reply": reply, "who": pt.name() }))
                    }
                    Err(e) => json(serde_json::json!({ "error": e })),
                }
            }
            // The month's spend, the ceiling and where donations go — public, because the
            // ceiling being visible is the point. Anyone can check what the bay has left.
            (Method::Get, "/api/meter") => json(meter.view()),
            // Through the server so the click is counted — measured conversion is the evidence
            // a funder asks for — then straight on to the payment page.
            (Method::Get, "/donate") => match meter.donate_url().map(str::to_string) {
                Some(to) => {
                    meter.click(&store);
                    Response::from_string("")
                        .with_status_code(302)
                        .with_header(Header::from_bytes(&b"Location"[..], to.as_bytes()).unwrap())
                }
                None => Response::from_string("no donation link is configured yet").with_status_code(404),
            },
            (Method::Get, "/api/chain") => {
                let t = tree.lock().unwrap();
                let who = param(&url, "player").and_then(|p| pubkey(&p));
                json(serde_json::json!({
                    "connected": chain.is_some(),
                    "voice": patient.is_some(),
                    "tree_id": t.tree_id,
                    "anchored": t.leaves.len(),
                    "relay": chain.as_ref().map(|c| c.relay_pubkey()),
                    // How many of the tree's leaves are *this* player's. Before the relay split
                    // there was one number here because there was one identity.
                    "proven": match (chain.as_ref(), who) {
                        (Some(c), Some(k)) => Some(c.proven_count(&k, t.tree_id)),
                        _ => None,
                    },
                }))
            }
            // Declare the run before it is played. The player signs the declaration; the chain
            // stamps the slot; the session keeps all of it so the record built at anchor time
            // carries exactly what the program will stamp into the leaf.
            (Method::Get, "/api/commit") => {
                let Some(c) = &chain else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no chain configured" })));
                    continue;
                };
                let Some(id) = param(&url, "id") else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no session" })));
                    continue;
                };
                let Some(who) = param(&url, "player").and_then(|p| pubkey(&p)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no player key" })));
                    continue;
                };
                let person = param(&url, "account").and_then(|p| pubkey(&p)).unwrap_or(who);
                let case = {
                    let map = sessions.lock().unwrap();
                    let Some(s) = map.get(&id) else {
                        drop(map);
                        let _ = req.respond(no_such_session());
                        continue;
                    };
                    sce_hash(&s.sce_json)
                };
                // The nonce is what keeps the case hidden from chain observers until reveal. It
                // never leaves this process except inside a debrief the player asks for.
                let nonce = {
                    use solana_sdk::signature::Signer;
                    solana_sdk::signature::Keypair::new().pubkey().to_bytes()
                };
                let hash = vitals_progress::record::commitment_hash(&case, &person.to_bytes(), &nonce);
                match c.prepare_commit(&who, &person, hash) {
                    Ok(p) => {
                        let msg = hex_bytes(&p.message());
                        pendings.lock().unwrap().insert(
                            who.to_string(),
                            PendingWork { pending: p, session: id.clone(), account: person,
                                          prove: None, commit: Some((hash, nonce)),
                                          index: 0, score: 0, level: None, link: false },
                        );
                        json(serde_json::json!({ "sign": msg }))
                    }
                    Err(e) => json(serde_json::json!({ "error": e })),
                }
            }
            (Method::Get, "/api/anchor") => {
                let id = param(&url, "id").unwrap_or_default();
                let caller = param(&url, "player");
                let Some(c) = chain.as_ref() else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no chain connected" })));
                    continue;
                };
                let mut map = sessions.lock().unwrap();
                let Some(s) = map.get_mut(&id).filter(|s| s.answers_to(caller.as_deref())) else {
                    let _ = req.respond(no_such_session());
                    continue;
                };
                if s.state.outcome().is_none() {
                    let _ = req.respond(json(serde_json::json!({ "error": "the run has not finished" })));
                    continue;
                }
                if s.anchored {
                    let _ = req.respond(json(serde_json::json!({ "error": "already anchored" })));
                    continue;
                }
                // Rebuild the run from the tape through the shared reducer rather than from the
                // live session, so what gets anchored is exactly what a verifier would recompute.
                let r = match replay(&s.sce_json, &s.tape) {
                    Ok(r) => r,
                    Err(e) => {
                        let _ = req.respond(json(serde_json::json!({ "error": e })));
                        continue;
                    }
                };
                // Whose run this is. It arrives from the browser and it is the key the browser
                // will sign with — the server has no way to produce that signature, which is what
                // makes the credential the player's rather than the server's.
                let Some(who) = param(&url, "player").and_then(|p| pubkey(&p)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no player key" })));
                    continue;
                };
                // The machine signs; the person owns. Absent an account the two are the same, which
                // is exactly what the very first run on a brand new browser is.
                let person = param(&url, "account").and_then(|p| pubkey(&p)).unwrap_or(who);
                let sce = sce_hash(&s.sce_json);
                // The commitment made before this run started. Anchoring without one is refused
                // here with a sentence rather than by the program with an error code — the
                // program will refuse it anyway, since it reads the commitment account and finds
                // nothing open, but the person typing deserves to know what was missing.
                let Some((chash, cslot, _nonce)) = s.commit else {
                    let _ = req.respond(json(serde_json::json!({
                        "error": "this run was never committed — the chain refuses runs that were not declared before play"
                    })));
                    continue;
                };
                let rec: AttemptRecord =
                    match record_for(person.to_bytes(), sce, sce, s.difficulty, false, &s.tape, &r, chash, cslot) {
                        Ok(rec) => rec,
                        Err(e) => {
                            let _ = req.respond(json(serde_json::json!({ "error": e })));
                            continue;
                        }
                    };
                let mut t = tree.lock().unwrap();
                t.leaves.push(rec.leaf());
                let tree_id = t.tree_id;
                let leaves = t.leaves.clone();
                let index = leaves.len() as u64 - 1;
                drop(t);
                match c.prepare_anchor(&who, &person, tree_id, &rec, &leaves) {
                    Ok((anchor, prove)) => {
                        let msg = hex_bytes(&anchor.message());
                        let msg2 = hex_bytes(&prove.message());
                        pendings.lock().unwrap().insert(
                            who.to_string(),
                            PendingWork { pending: anchor, prove: Some(prove),
                                          session: id.clone(), account: person, commit: None,
                                          index, score: rec.score(), level: None, link: false },
                        );
                        json(serde_json::json!({ "sign": msg, "sign2": msg2 }))
                    }
                    Err(e) => {
                        // Building it failed, so the leaf was never anchored. Take it back off the
                        // list or every later proof is built against a tree that does not exist.
                        tree.lock().unwrap().leaves.pop();
                        json(serde_json::json!({ "error": e }))
                    }
                }
            }
            (Method::Get, "/api/claim") => {
                let level: u8 = param(&url, "level").and_then(|v| v.parse().ok()).unwrap_or(2);
                let Some(c) = chain.as_ref() else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no chain connected" })));
                    continue;
                };
                let Some(who) = param(&url, "player").and_then(|p| pubkey(&p)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no player key" })));
                    continue;
                };
                let id = param(&url, "account").and_then(|p| pubkey(&p)).unwrap_or(who);
                let tree_id = tree.lock().unwrap().tree_id;
                match c.prepare_claim(&who, &id, tree_id, level) {
                    Ok(p) => {
                        let msg = hex_bytes(&p.message());
                        pendings.lock().unwrap().insert(
                            who.to_string(),
                            PendingWork { pending: p, session: String::new(), account: id, prove: None, commit: None,
                                          index: 0, score: 0, level: Some(level), link: false },
                        );
                        json(serde_json::json!({ "sign": msg }))
                    }
                    Err(e) => json(serde_json::json!({ "error": e })),
                }
            }
            // Who this machine is, and whose record it may write to.
            (Method::Get, "/api/account") => {
                let Some(c) = chain.as_ref() else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no chain connected" })));
                    continue;
                };
                let Some(dev) = param(&url, "device").and_then(|p| pubkey(&p)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no device key" })));
                    continue;
                };
                let person = param(&url, "account").and_then(|p| pubkey(&p)).unwrap_or(dev);
                let acct = c.account(&person);
                json(serde_json::json!({
                    "account": person.to_string(),
                    "open": acct.is_some(),
                    // Whether *this* machine may act for that person. A machine that has been
                    // named but not yet linked is a machine that can watch and not play.
                    "linked": acct.as_ref().map(|a| a.allows(&dev)).unwrap_or(person == dev),
                    "devices": acct.as_ref().map(|a| a.authorities.len()).unwrap_or(0),
                    // How many runs this person has ever declared, as the chain counted them —
                    // the number the commit-reveal design exists to make undeniable: five
                    // practice runs need five visible commitments.
                    "started": c.commitment(&person).map(|cm| cm.started),
                }))
            }
            // Reading somebody's level is not a privileged act, and that is the whole point:
            // a score you can only see on the machine that earned it is not a credential.
            (Method::Get, "/api/progress") => {
                let Some(c) = chain.as_ref() else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no chain connected" })));
                    continue;
                };
                let Some(person) = param(&url, "account").and_then(|p| pubkey(&p)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no account" })));
                    continue;
                };
                match c.progress(&person) {
                    Some(pr) => json(serde_json::json!({
                        "account": person.to_string(),
                        "level": pr.level,
                        "level_name": chain::level_name(pr.level),
                        "attempts": pr.attempts_counted,
                        "distinct": pr.distinct_cases,
                        "xp": pr.xp,
                    })),
                    None => json(serde_json::json!({
                        "account": person.to_string(), "level": serde_json::Value::Null,
                        "message": "nothing claimed yet",
                    })),
                }
            }
            // Link or unlink a machine. Signed by one that is already trusted.
            (Method::Get, "/api/link") => {
                let Some(c) = chain.as_ref() else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no chain connected" })));
                    continue;
                };
                let Some(dev) = param(&url, "player").and_then(|p| pubkey(&p)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no player key" })));
                    continue;
                };
                let person = param(&url, "account").and_then(|p| pubkey(&p)).unwrap_or(dev);
                let Some(other) = param(&url, "device").and_then(|p| pubkey(&p)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no device to link" })));
                    continue;
                };
                let on = param(&url, "off").is_none();
                // prepare_link opens the account itself when there is not one yet, so the
                // transaction always does what the button said.
                match c.prepare_link(&dev, &person, &other, on) {
                    Ok(p) => {
                        let msg = hex_bytes(&p.message());
                        pendings.lock().unwrap().insert(
                            dev.to_string(),
                            PendingWork { pending: p, session: String::new(), account: person, prove: None, commit: None,
                                          index: 0, score: 0, level: None, link: true },
                        );
                        json(serde_json::json!({ "sign": msg }))
                    }
                    Err(e) => json(serde_json::json!({ "error": e })),
                }
            }
            // The other half. The browser signed the bytes we handed it; we drop the signature
            // into its slot and send. If it does not verify, nothing is sent.
            (Method::Get, "/api/submit") => {
                let Some(c) = chain.as_ref() else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no chain connected" })));
                    continue;
                };
                let Some(who) = param(&url, "player").and_then(|p| pubkey(&p)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no player key" })));
                    continue;
                };
                let Some(sig) = param(&url, "sig").and_then(|h| sig64(&h)) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "no signature" })));
                    continue;
                };
                let Some(work) = pendings.lock().unwrap().remove(&who.to_string()) else {
                    let _ = req.respond(json(serde_json::json!({ "error": "nothing waiting to be signed" })));
                    continue;
                };
                // Only an anchor put a leaf on the list, so only an anchor takes one back off.
                let speculative = work.level.is_none() && !work.link && work.commit.is_none();
                let tx = match work.pending.signed(&sig) {
                    Ok(tx) => tx,
                    Err(e) => {
                        if speculative {
                            tree.lock().unwrap().leaves.pop();
                        }
                        let _ = req.respond(json(serde_json::json!({ "error": e })));
                        continue;
                    }
                };
                let id = work.account;
                if let Some((hash, nonce)) = work.commit {
                    let _ = req.respond(match c.submit(&tx) {
                        Ok(()) => match c.commitment(&id) {
                            // Read back rather than assumed: the slot was assigned on chain, and
                            // the record built at anchor time must carry the same one the program
                            // will stamp into the leaf — a guessed slot forks the server's leaf
                            // list from the tree.
                            Some(cm) if cm.open && cm.hash == hash => {
                                let mut map = sessions.lock().unwrap();
                                if let Some(s) = map.get_mut(&work.session) {
                                    s.commit = Some((hash, cm.slot, nonce));
                                    persist(&store, &work.session, s, true);
                                }
                                json(serde_json::json!({ "committed": true, "started": cm.started }))
                            }
                            _ => json(serde_json::json!({
                                "error": "the commit landed but could not be read back — try again"
                            })),
                        },
                        Err(e) => json(serde_json::json!({ "error": e })),
                    });
                    continue;
                }
                if work.link {
                    let _ = req.respond(match c.submit(&tx) {
                        Ok(()) => {
                            let n = c.account(&id).map(|a| a.authorities.len()).unwrap_or(0);
                            json(serde_json::json!({ "linked": true, "devices": n }))
                        }
                        Err(e) => json(serde_json::json!({ "error": e })),
                    });
                    continue;
                }
                match (c.submit(&tx), work.level) {
                    (Ok(()), Some(_)) => match c.claimed(&id) {
                        Ok(m) => json(serde_json::json!({ "granted": true, "message": m })),
                        Err(m) => json(serde_json::json!({ "granted": false, "message": m })),
                    },
                    (Ok(()), None) => {
                        // The tree really changed, so write it before anything else can fail.
                        let t = tree.lock().unwrap();
                        let _ = store.put(TREE, &tree_key, &*t);
                        drop(t);
                        // The proof rides as a second transaction — the pair stopped fitting in
                        // one packet when the record grew. The anchor is already in; a proof that
                        // fails here leaves an intact state (anchored, provable later), so the
                        // error is reported rather than unwound.
                        if let Some(prove) = work.prove {
                            let sent = param(&url, "sig2")
                                .and_then(|h| sig64(&h))
                                .ok_or_else(|| "anchored, but no second signature for the proof".to_string())
                                .and_then(|s2| prove.signed(&s2))
                                .and_then(|tx2| c.submit(&tx2));
                            if let Err(e) = sent {
                                let _ = req.respond(json(serde_json::json!({
                                    "anchored": true, "proven": false,
                                    "error": format!("anchored, but the proof did not land: {e}"),
                                })));
                                continue;
                            }
                        }
                        let mut map = sessions.lock().unwrap();
                        if let Some(s) = map.get_mut(&work.session) {
                            s.anchored = true;
                            persist(&store, &work.session, s, true);
                        }
                        drop(map);
                        // Read the id out and let go of the lock. A `tree.lock()` written inside
                        // the match scrutinee stays alive for the whole match, so taking it again
                        // in an arm deadlocks the one thread this server has — which is not a slow
                        // request, it is every request from then on.
                        let tree_id = tree.lock().unwrap().tree_id;
                        match c.anchored(&id, tree_id, work.index) {
                            Ok(a) => json(serde_json::json!({
                                "index": a.index, "root": a.root, "leaves": a.leaves,
                                "proven": a.proven, "score": work.score,
                                "counted": c.proven_count(&id, tree_id),
                            })),
                            Err(e) => json(serde_json::json!({ "error": e })),
                        }
                    }
                    (Err(e), Some(_)) => json(serde_json::json!({ "granted": false, "message": e })),
                    (Err(e), None) => {
                        // Nothing landed on chain, so the leaf is not in the tree.
                        tree.lock().unwrap().leaves.pop();
                        json(serde_json::json!({ "error": e }))
                    }
                }
            }
            _ => Response::from_string("not found").with_status_code(404),
        };
        let _ = req.respond(resp);
    }
}

/// What the browser is waiting to sign, and what to do once it has.
struct PendingWork {
    pending: chain::Pending,
    /// The proof transaction that follows a successful anchor. Two transactions because the pair
    /// stopped fitting in one packet when the record grew — see `prepare_anchor`. The player
    /// signs both messages together; the server submits them in order.
    prove: Option<chain::Pending>,
    /// Which run this anchors. Empty for a claim.
    session: String,
    /// Set when this transaction is a pre-run commitment: (hash, nonce). On success the slot is
    /// read back from the account — the program assigned it, so only the chain knows it — and
    /// all three land in the session for the record to use at anchor time.
    commit: Option<([u8; 32], [u8; 32])>,
    /// Whose record this lands on — not necessarily the key that signs it.
    account: solana_sdk::pubkey::Pubkey,
    index: u64,
    score: u32,
    /// Set for a claim, `None` for an anchor.
    level: Option<u8>,
    /// True when this transaction only moves devices around and touches no tree.
    link: bool,
}

/// The apex is the company's front door and nothing else (decided 2026-08-25): the game, its
/// APIs and its session state live on the devnet host. One instance serves both names, so the
/// split is the Host header — an allowlist of exactly one special name, with every other name
/// (devnet, run.app, localhost) keeping the full app unchanged.
const APEX: &str = "vitals.academy";
const GAME_ORIGIN: &str = "https://devnet.vitals.academy";

fn host_of(req: &tiny_http::Request) -> String {
    req.headers()
        .iter()
        .find(|h| h.field.equiv("host"))
        .map(|h| h.value.as_str().trim().to_ascii_lowercase())
        .and_then(|h| h.split(':').next().map(str::to_string))
        .unwrap_or_default()
}

/// What the apex does with a URL: `None` serves the landing, otherwise the permanent home of
/// that path on the game origin — a deep link pasted against the apex still lands somewhere
/// real, query string and all. Decided on the path alone so `/?utm_source=...` stays a landing.
fn apex_target(url: &str) -> Option<String> {
    let path = url.split('?').next().unwrap_or("/");
    (path != "/").then(|| format!("{GAME_ORIGIN}{url}"))
}

/// Where to listen, with the platform's word winning over ours.
///
/// Cloud Run assigns `PORT` and health-probes exactly that port; a container that binds anything
/// else boots perfectly and never becomes healthy — which is precisely how the first public
/// deploy failed, the app on its own 8474 while the probe watched 8080. So `PORT`, when given,
/// is not a preference to weigh against `VITALS_WEB_BIND`; it is the address the platform will
/// judge us by. Everywhere else `VITALS_WEB_BIND` decides, and the default stays loopback so a
/// laptop never opens a public port by accident.
fn bind_addr(platform_port: Option<&str>, configured: Option<&str>) -> String {
    match platform_port {
        Some(p) if !p.is_empty() => format!("0.0.0.0:{p}"),
        _ => configured.map(str::to_string).unwrap_or_else(|| "127.0.0.1:8474".into()),
    }
}

/// A player key as the browser sends it: base58, and it has to be a real curve point or the
/// transaction it is put into can never be signed.
fn pubkey(s: &str) -> Option<solana_sdk::pubkey::Pubkey> {
    let raw = bs58_to_32(s)?;
    let k = solana_sdk::pubkey::Pubkey::new_from_array(raw);
    (k.to_string() == s).then_some(k)
}

fn hex_bytes(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// A 64-byte signature as hex.
fn sig64(h: &str) -> Option<[u8; 64]> {
    if h.len() != 128 {
        return None;
    }
    let mut out = [0u8; 64];
    for (i, b) in out.iter_mut().enumerate() {
        *b = u8::from_str_radix(h.get(i * 2..i * 2 + 2)?, 16).ok()?;
    }
    Some(out)
}

/// Decode a base58 pubkey into raw bytes.
fn bs58_to_32(s: &str) -> Option<[u8; 32]> {
    const A: &[u8] = b"123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
    let mut out = vec![0u8; 32];
    for ch in s.bytes() {
        let mut carry = A.iter().position(|&c| c == ch)?;
        for b in out.iter_mut().rev() {
            carry += 58 * (*b as usize);
            *b = (carry & 0xff) as u8;
            carry >>= 8;
        }
        if carry != 0 {
            return None;
        }
    }
    out.try_into().ok()
}

/// The phrase a device pick sends through the intervention matcher.
///
/// One catalogue, and it carries the number: a learner who sets the flowmeter to 15 should see
/// 15 in the chart, not the scenario's canonical dose.
fn kit_phrase(dev: &str, set: Option<f64>) -> Option<String> {
    Some(match dev {
        "o2" => format!("oxygen face mask {} lpm", set.unwrap_or(10.0) as i64),
        "iv" => format!("iv access normal saline {} ml/hr", set.unwrap_or(999.0) as i64),
        "ett" => "intubate, secure the airway".to_string(),
        "supine" => "lay her flat, legs up".to_string(),
        "defib" => format!("defibrillate {} j", set.unwrap_or(200.0) as i64),
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── things that arrive from the network ─────────────────────────────────
    //
    // Every one of these turns an attacker-controlled string into something the rest of the
    // server trusts — a public key, a signature, a query value. They had no tests at all.

    #[test]
    fn a_pubkey_must_round_trip_exactly() {
        // A real one, and the check that makes it real: base58 has no canonical padding, so a
        // string that decodes to 32 bytes is not necessarily the string those bytes encode to.
        let real = "AStZxZ8XgH9nSKarLT4MzUrY8HM5LtExzDaN9SDoaKiq";
        assert_eq!(pubkey(real).map(|k| k.to_string()).as_deref(), Some(real));
    }

    /// Forty-three characters is a real address, not a truncated one. A pubkey is 32 bytes and
    /// base58 spends 43 or 44 characters on them depending on the leading byte — so a length
    /// check would reject roughly one address in 256, and only for the people who happen to hold
    /// one. The round-trip is the check; the length never was.
    #[test]
    fn a_forty_three_character_key_is_valid() {
        let short = "AStZxZ8XgH9nSKarLT4MzUrY8HM5LtExzDaN9SDoaKi";
        assert_eq!(short.len(), 43);
        assert_eq!(pubkey(short).map(|k| k.to_string()).as_deref(), Some(short));
    }

    #[test]
    fn pubkey_refuses_everything_that_is_not_one() {
        for bad in [
            "",
            "notapubkey",
            "0OIl",                                          // the four base58 excludes
            "AStZxZ8XgH9nSKarLT4MzUrY8HM5LtExzDaN9SDoaKiqq", // one char long
            "1AStZxZ8XgH9nSKarLT4MzUrY8HM5LtExzDaN9SDoaKiq", // leading zero byte, different string
            "../../etc/passwd",
            "AStZxZ8XgH9nSKarLT4MzUrY8HM5LtExzDaN9SDoaKi ",  // trailing space
        ] {
            assert!(pubkey(bad).is_none(), "accepted {bad:?}");
        }
    }

    #[test]
    fn a_signature_is_exactly_sixty_four_bytes_of_hex() {
        let ok = "ab".repeat(64);
        assert_eq!(sig64(&ok).map(|s| s[0]), Some(0xab));
        assert_eq!(sig64(&ok).map(|s| s.len()), Some(64));
        for bad in [
            String::new(),
            "ab".repeat(63),          // short
            "ab".repeat(65),          // long
            "zz".repeat(64),          // not hex
            format!("{}gg", "ab".repeat(63)),
            format!(" {}", "ab".repeat(64)).trim_end().to_string(), // leading space, right length
        ] {
            assert!(sig64(&bad).is_none(), "accepted {:?}", &bad[..bad.len().min(12)]);
        }
    }

    #[test]
    fn hex_round_trips_through_sig64() {
        let bytes: [u8; 64] = std::array::from_fn(|i| (i * 7 % 251) as u8);
        assert_eq!(sig64(&hex_bytes(&bytes)), Some(bytes));
    }

    #[test]
    fn hex_is_lowercase_and_zero_padded() {
        assert_eq!(hex_bytes(&[0, 1, 15, 16, 255]), "00010f10ff");
    }

    #[test]
    fn base58_decodes_the_known_all_zero_key() {
        // 32 zero bytes encode as 32 '1's, and nothing else does.
        assert_eq!(bs58_to_32(&"1".repeat(32)), Some([0u8; 32]));
    }

    // ── query parsing ───────────────────────────────────────────────────────

    #[test]
    fn param_reads_values_and_decodes_them() {
        let u = "/api/step?id=s1&do=oxygen%20face%20mask&tick=30";
        assert_eq!(param(u, "id").as_deref(), Some("s1"));
        assert_eq!(param(u, "do").as_deref(), Some("oxygen face mask"));
        assert_eq!(param(u, "tick").as_deref(), Some("30"));
        assert_eq!(param(u, "missing"), None);
    }

    #[test]
    fn param_does_not_match_a_key_that_merely_ends_with_the_one_asked_for() {
        // `account` must not be answered by `subaccount`, or a caller can aim a request at
        // somebody else's record by naming a parameter carefully.
        let u = "/api?subaccount=theirs&account=mine";
        assert_eq!(param(u, "account").as_deref(), Some("mine"));
    }

    // ── the apex ────────────────────────────────────────────────────────────

    /// The front door serves the landing and moves everything else — path, query and all — to
    /// the game origin. A deep link shared from the game must survive being pasted on the apex.
    #[test]
    fn the_apex_keeps_the_landing_and_redirects_the_rest() {
        assert_eq!(apex_target("/"), None);
        assert_eq!(apex_target("/?utm_source=colosseum"), None, "campaign links are landings");
        assert_eq!(apex_target("/play").as_deref(), Some("https://devnet.vitals.academy/play"));
        assert_eq!(
            apex_target("/api/chain?player=abc").as_deref(),
            Some("https://devnet.vitals.academy/api/chain?player=abc"),
        );
    }

    // ── where to listen ─────────────────────────────────────────────────────

    /// Cloud Run probes the port it assigned, not the one we prefer. An app that boots
    /// perfectly on the wrong port fails in the way that is hardest to see from inside.
    #[test]
    fn the_platforms_port_wins_and_binds_publicly() {
        assert_eq!(bind_addr(Some("8080"), None), "0.0.0.0:8080");
        assert_eq!(bind_addr(Some("8080"), Some("0.0.0.0:8474")), "0.0.0.0:8080");
    }

    #[test]
    fn without_a_platform_port_the_operator_decides_and_the_default_is_loopback() {
        assert_eq!(bind_addr(None, Some("0.0.0.0:8474")), "0.0.0.0:8474");
        assert_eq!(bind_addr(None, None), "127.0.0.1:8474");
        // An empty PORT is no PORT — some shells export the variable before it has a value.
        assert_eq!(bind_addr(Some(""), None), "127.0.0.1:8474");
    }

    // ── which routes need a token ───────────────────────────────────────────

    #[test]
    fn guarding_covers_everything_that_spends_or_signs() {
        for p in ["/api/anchor", "/api/claim", "/api/commit", "/api/say"] {
            assert!(guarded(p), "{p} makes the server sign or spend");
        }
        for p in ["/", "/play", "/api/new", "/api/step", "/api/kit", "/api/tape", "/api/chain",
                  "/api/meter", "/donate"] {
            assert!(!guarded(p), "{p} is play, and a kiosk must not need a token to play");
        }
    }

    // ── scenario table ──────────────────────────────────────────────────────

    #[test]
    fn every_episode_has_a_title_a_difficulty_and_a_file() {
        for ep in ["ep1", "ep2", "ep3", "ep4", "ep5"] {
            assert!(title(ep).starts_with(&ep.to_uppercase()), "{ep} title is {}", title(ep));
            let p = scenario_path(ep);
            assert!(p.exists(), "{ep}: {} is missing", p.display());
        }
        // The ladder is meant to climb.
        assert_eq!(difficulty("ep1"), Difficulty::Student);
        assert_eq!(difficulty("ep2"), Difficulty::Intern);
        assert_eq!(difficulty("ep5"), Difficulty::Resident);
    }

    #[test]
    fn an_unknown_episode_falls_back_rather_than_panicking() {
        assert!(scenario_path("../../etc/passwd").exists(), "unknown ids fall back to EP1");
        assert_eq!(difficulty("nonsense"), Difficulty::Student);
    }

    // ── the device picker ───────────────────────────────────────────────────

    #[test]
    fn kit_phrases_carry_the_number_the_learner_dialled() {
        assert_eq!(kit_phrase("o2", Some(6.0)).as_deref(), Some("oxygen face mask 6 lpm"));
        assert_eq!(kit_phrase("iv", Some(250.0)).as_deref(), Some("iv access normal saline 250 ml/hr"));
        assert_eq!(kit_phrase("defib", Some(200.0)).as_deref(), Some("defibrillate 200 j"));
        assert_eq!(kit_phrase("nothing", None), None);
    }

    #[test]
    fn kit_phrases_without_a_setting_still_read_as_orders() {
        assert_eq!(kit_phrase("ett", None).as_deref(), Some("intubate, secure the airway"));
        assert!(kit_phrase("o2", None).unwrap().contains("10 lpm"), "falls back to the scenario dose");
    }

}
